#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.20
#  in conjunction with Tcl version 8.6
#    Feb 01, 2019 12:08:50 PM MST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global neighbors
    neighbors = tk.StringVar()
    global che121
    che121 = tk.StringVar()
    global che178
    che178 = tk.StringVar()
    global che49
    che49 = tk.StringVar()
    global che50
    che50 = tk.StringVar()
    global che51
    che51 = tk.StringVar()
    global che63
    che63 = tk.StringVar()
    global che64
    che64 = tk.StringVar()
    global che65
    che65 = tk.StringVar()
    global che66
    che66 = tk.StringVar()
    global che103
    che103 = tk.StringVar()
    global che104
    che104 = tk.StringVar()
    global che105
    che105 = tk.StringVar()
    global che107
    che107 = tk.StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import GUI
    GUI.vp_start_gui()




